# Generated by Django 5.2.3 on 2025-06-12 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuit_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('constructor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_run', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('round', models.CharField(max_length=100)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.circuit')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.season')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driver')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('q1', models.CharField(blank=True, max_length=100, null=True)),
                ('q2', models.CharField(blank=True, max_length=100, null=True)),
                ('q3', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driver')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.race')),
            ],
            options={
                'unique_together': {('date', 'driver_id')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('grid', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('position_text', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('laps', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('constructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.constructor')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.race')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driver')),
            ],
            options={
                'unique_together': {('date', 'driver_id')},
            },
        ),
        migrations.CreateModel(
            name='DriverTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_season_number', models.CharField(max_length=100)),
                ('constructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.constructor')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driver')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.season')),
            ],
            options={
                'unique_together': {('season_id', 'driver_id')},
            },
        ),
        migrations.CreateModel(
            name='Driverstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('positionText', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('wins', models.CharField(max_length=100)),
                ('constructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.constructor')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.driver')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.season')),
            ],
            options={
                'unique_together': {('season_id', 'driver_id')},
            },
        ),
        migrations.CreateModel(
            name='Constructorstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('positionText', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('wins', models.CharField(max_length=100)),
                ('constructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.constructor')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.season')),
            ],
            options={
                'unique_together': {('season_id', 'constructor_id')},
            },
        ),
    ]
