# Generated by Django 5.2.3 on 2025-06-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet_id',
            new_name='bet',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='circuit',
            old_name='circuit_id',
            new_name='circuit',
        ),
        migrations.RenameField(
            model_name='constructor',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='constructorstanding',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='constructorstanding',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='driverstanding',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='driverstanding',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='driverstanding',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='driverteam',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='driverteam',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='driverteam',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='qualifyingresult',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='circuit_id',
            new_name='circuit',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='constructor_id',
            new_name='constructor',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season_id',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='constructorstanding',
            unique_together={('season', 'constructor')},
        ),
        migrations.AlterUniqueTogether(
            name='driverstanding',
            unique_together={('season', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='driverteam',
            unique_together={('season', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingresult',
            unique_together={('date', 'driver')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('date', 'driver')},
        ),
    ]
