# Generated by Django 5.2.3 on 2025-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_bet_id_bet_bet_rename_driver_id_bet_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='circuit',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='constructor',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
