# Generated by Django 5.2.3 on 2025-06-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_result_fastest_lap_alter_result_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
