# Generated by Django 5.2.3 on 2025-06-14 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_betstat'),
        ('catalog', '0005_delete_bet_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('bet_top_3', models.JSONField(default=list)),
                ('bet_last_5', models.JSONField(default=list)),
                ('bet_last_10', models.JSONField(default=list)),
                ('safety_car', models.BooleanField(default=False)),
                ('bet_fastest_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastest_lap_bets', to='catalog.driver')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.group')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'race')},
            },
        ),
    ]
